// React/src/components/Chart/Chart.tsx
import React, {
  useEffect, useMemo, useRef, useState,
} from 'react';
import { IStroke } from '~/interfaces/IStroke';
import style from './Chart.module.scss';

const calculateInterest = (max: number, current: number) => {
  return ((current * 100) / max) / 100;
};
function divideNumber(num: number, arr: [number, number, number, number]) {
  let number = num;

  const firstPart = Math.min(number, arr[0]);
  number -= firstPart;

  const secondPart = Math.min(number, arr[1]);
  number -= secondPart;

  const thirdPart = Math.min(number, arr[2]);
  number -= thirdPart;

  const fourthPart = number;

  return [ calculateInterest(arr[0], firstPart),
    calculateInterest(arr[1], secondPart),
    calculateInterest(arr[2], thirdPart),
    calculateInterest(arr[3], fourthPart) ];
}
const actualKeys: Record<string, number> = {};
function animate(arg: {
  from: number, to: number,
  speed: number,
  setter: React.Dispatch<React.SetStateAction<IStroke[]>>,
  key: string
  id: number
  data: IStroke[],
}) {
  let startTime: number;
  const {
    speed, to, from, setter, key, id, data,
  } = arg;

  const currentKey = Math.random();

  actualKeys[key] = currentKey;

  const step = (time: number) => {
    if (actualKeys[key] !== currentKey) {
      return;
    }
    if (!startTime) {
      startTime = time;
    }

    const elapsed = time - startTime;
    const progress = Math.min(elapsed / speed, 1);
    const value = from + (to - from) * progress;

    setter((prev) => data.map((item, i) => {
      if (item.id !== id) {
        return {
          ...item,
          progress: Math.max(prev[i]?.progress || data[i]?.progress || 0.01, 0.01),
        };
      }

      return {
        ...item,
        progress: value,

      };
    }));

    if (progress < 1) {
      requestAnimationFrame(step);
    }
  };

  requestAnimationFrame(step);
}
type Props = {
  data: IStroke[]
  gap?: number
  strokeWidth?: number
  radius?: number
  circleCenterX?: number
  circleCenterY?: number
};

const startValues: Record<number, {
  strokeWidth: number,
  r: number,
}> = {
  1: {
    strokeWidth: 4,
    r: 20,
  },
  2: {
    strokeWidth: 4,
    r: 20,
  },
  3: {
    strokeWidth: 4,
    r: 20,
  },
  4: {
    strokeWidth: 4,
    r: 20,
  },
  5: {
    strokeWidth: 4,
    r: 19,
  },
  6: {
    strokeWidth: 3,
    r: 19,
  },
  7: {
    strokeWidth: 3,
    r: 17,
  },
  8: {
    strokeWidth: 2.5,
    r: 17,
  },
  9: {
    strokeWidth: 2,
    r: 17,
  },
  10: {
    strokeWidth: 2,
    r: 16,
  },

};

export const Chart: React.FC<Props> = ({
  data, gap = 0.5, strokeWidth, radius, circleCenterX, circleCenterY,
}) => {
  const [ localData, setLocalData ] = useState<IStroke[]>(data);
  const dataLength = useMemo(() => data.length, [ data.length ]);
  const charStrokeWidth = useMemo(() => strokeWidth
  || startValues[dataLength].strokeWidth, [ dataLength, strokeWidth ]);
  const gapWithStrokeWidth = useMemo(() => charStrokeWidth + gap, [ gap, charStrokeWidth ]);
  const r = useMemo(() => radius || startValues[dataLength].r, [ dataLength, radius ]);
  const circleCoef = useMemo(() => 2 * Math.PI, []);

  useEffect(() => {
    localData.forEach((dataItem, i) => {
      if (data[i]) {
        animate({
          setter: setLocalData,
          speed: 500,
          from: dataItem.progress || data[i].progress,
          to: Math.min(data[i].progress, 100),
          key: `strokeWidth ${ dataItem.id }`,
          id: dataItem.id,
          data,
        });
      }
    });
  }, [ data ]);

  const rLastItem = useMemo(
    () => r + ((localData.length - 1) * gapWithStrokeWidth),
    [ gapWithStrokeWidth, localData.length, r ],
  );

  const localCircleCenterX = useMemo(() => circleCenterX || 40, [ circleCenterX ]);
  const localCircleCenterY = useMemo(() => circleCenterY || 60, [ circleCenterY ]);

  const renderStrokes = useMemo(() => {
    return localData.map((item, i) => {
      const newR = r + (i * gapWithStrokeWidth);
      const secondDash = (newR) * circleCoef;

      const circleCenterBefore = localCircleCenterX - 0.2;
      const circleCenterAfter = localCircleCenterY + 0.1;

      const centerLineY = localCircleCenterY - r - i * gapWithStrokeWidth;
      const bottomLineX = localCircleCenterX + r + i * gapWithStrokeWidth;
      const topLineY1 = localCircleCenterY - rLastItem - charStrokeWidth;
      const strokeDasharray = `${ (secondDash / 2) * 1.5 },${ secondDash }`;
      const bottomLineY1 = localCircleCenterY - r + charStrokeWidth;

      const topLineSize = topLineY1;
      const bottomLineSize = circleCenterAfter - (localCircleCenterY - r + charStrokeWidth);
      const circleSize = (2 * Math.PI * r) * (3 / 4);
      const centerLineSize = 100 - circleCenterBefore;
      const totalSize = topLineSize + bottomLineSize + circleSize + centerLineSize;

      const parts = divideNumber(item.progress, [
        calculateInterest(totalSize, topLineSize) * 100,
        calculateInterest(totalSize, bottomLineSize) * 100,
        calculateInterest(totalSize, circleSize) * 100,
        calculateInterest(totalSize, centerLineSize) * 100,
      ]);

      const fillCenterLineY = circleCenterBefore + ((circleCenterAfter) * parts[3]);
      const fillBottomLineX = bottomLineY1 + ((circleCenterAfter - bottomLineY1) * parts[1]);
      const fillTopLineY1 = topLineY1 * parts[0];

      const fillStrokeDasharray = `${ (secondDash / 2) * (1.5 * parts[2]) },${ secondDash }`;

      return {
        newR,
        secondDash,
        centerLineY,
        bottomLineX,
        topLineY1,
        strokeDasharray,
        bottomLineY1,
        fillCenterLineY,
        fillBottomLineX,
        fillTopLineY1,
        fillStrokeDasharray,
        circleCenterBefore,
        circleCenterAfter,
        ...item,
      };
    });
  }, [ localCircleCenterX,
    localCircleCenterY, circleCoef,
    gapWithStrokeWidth, localData, r, rLastItem,
    charStrokeWidth ]);

  const chartRef = useRef<SVGSVGElement | null>(null);
  const chartSize = useMemo(() => {
    if (chartRef.current) {
      const sizeValue = Math.min(chartRef.current?.clientWidth, chartRef.current?.clientHeight);
      return sizeValue / 500;
    }

    return 0;
  }, [ chartRef.current?.clientWidth, chartRef.current?.clientHeight ]);

  return (
    <div className={ style['chart-wrapper'] }>
      <svg
        ref={ chartRef }
        className={ style.chart }
        viewBox="0 0 100 100"
      >
        {renderStrokes.map(({
          newR,
          centerLineY,
          bottomLineX,
          topLineY1,
          strokeDasharray,
          fillCenterLineY,
          fillBottomLineX,
          fillTopLineY1,
          fillStrokeDasharray,
          progress, color,
          id,
          circleCenterBefore,
          circleCenterAfter,
        }) => {
          return (
            <>
              <line
                x1={ bottomLineX }
                x2={ bottomLineX }
                y1={ topLineY1 }
                y2={ 0 }
                strokeWidth={ charStrokeWidth }
                stroke="#cccccc"
                key={ `${ id + progress }top` }
              />
              <line
                x1={ bottomLineX }
                x2={ bottomLineX }
                y1={ circleCenterAfter }
                y2={ localCircleCenterY - r + charStrokeWidth }
                strokeWidth={ charStrokeWidth }
                stroke="#cccccc"
                key={ `${ id + progress }bottom` }
              />
              <circle
                key={ `${ id + progress }circle` }
                r={ newR }
                cx={ localCircleCenterX }
                cy={ localCircleCenterY }
                className="pie"
                strokeWidth={ charStrokeWidth }
                stroke="#cccccc"
                strokeDasharray={ strokeDasharray }
                fill="none"
              />
              <line
                x1={ circleCenterBefore }
                x2="100"
                y1={ centerLineY }
                y2={ centerLineY }
                strokeWidth={ charStrokeWidth }
                stroke="#cccccc"
                key={ `${ id + progress }center` }
              />

              <line
                x1={ bottomLineX }
                x2={ bottomLineX }
                y1={ fillTopLineY1 }
                y2={ 0 }
                strokeWidth={ charStrokeWidth }
                key={ `${ id }top` }
                stroke={ color }
              />
              <line
                x1={ bottomLineX }
                x2={ bottomLineX }
                y2={ fillBottomLineX }
                y1={ localCircleCenterY - r + charStrokeWidth }
                strokeWidth={ charStrokeWidth }
                key={ `${ id }bottom` }
                stroke={ color }
              />
              <circle
                key={ `${ id }circle` }
                r={ newR }
                cx={ localCircleCenterX }
                cy={ localCircleCenterY }
                className="pie"
                strokeWidth={ charStrokeWidth }
                stroke={ color }
                strokeDasharray={ fillStrokeDasharray }
                fill="none"
              />
              <line
                x1={ circleCenterBefore }
                x2={ fillCenterLineY }
                y1={ centerLineY }
                y2={ centerLineY }
                strokeWidth={ charStrokeWidth }
                stroke={ color }
                key={ `${ id }center` }
              />
            </>
          );
        })}
      </svg>
      <div
        className={ style['chart-info'] }
        style={ {
          top: `${ localCircleCenterY }%`,
          left: `${ localCircleCenterX }%`,
          transform: `translate(-50%, -50%) scale(${ 1 * chartSize })`,
        } }
      >
        <span
          className={ style['main-text'] }
        >
          9999
        </span>
        <span
          className={ style['second-text'] }
        >
          kgCO2e
        </span>
      </div>

    </div>
  );
};

// Vue/src/components/Chart.vue
<script setup lang="ts">
import type { IStroke } from '@/interfaces/IStroke';
import type { IStrokeDetailed } from '@/interfaces/IStrokeDetailed';
import { onMounted, reactive, ref, toRefs, watch } from 'vue';

const calculateInterest = (max: number, current: number) => {
  return ((current * 100) / max) / 100;
};

function divideNumber(num: number, arr: [number, number, number, number]) {
  let number = num;

  const firstPart = Math.min(number, arr[0]);
  number -= firstPart;

  const secondPart = Math.min(number, arr[1]);
  number -= secondPart;

  const thirdPart = Math.min(number, arr[2]);
  number -= thirdPart;

  const fourthPart = number;

  return [calculateInterest(arr[0], firstPart),
  calculateInterest(arr[1], secondPart),
  calculateInterest(arr[2], thirdPart),
  calculateInterest(arr[3], fourthPart)];
}

function animate(args: {
  items: Array<{
    from: number,
    to: number,
    id: number
  }>;
  speed: number,
}) {
  let startTime: number;
  const {
    speed, items
  } = args;

  const step = (time: number) => {
    if (!startTime) {
      startTime = time;
    }
    let requireAnimationFrame = false;
    const result: IStroke[] = props.data.map((e) => ({ ...e }));
    for (const { id, from, to } of items) {

      const elapsed = time - startTime;
      const progress = Math.min(elapsed / speed, 1);
      const value = from + (to - from) * progress;
      if (progress < 1) {
        requireAnimationFrame = true;
      }
      const item = result.find((e) => e.id === id);
      if (item) {
        item.progress = value
      }
    }
    strokes.splice(0)
    strokes.push(...updateStrokes(result));

    if (requireAnimationFrame) {
      requestAnimationFrame(step);
    }
  };

  requestAnimationFrame(step);
}

const updateStrokes = (inputData: Array<IStroke>): IStrokeDetailed[] => {
  return inputData.map((item, i) => {
    const newR = r + (i * gapWithStrokeWidth);
    const secondDash = (newR) * circleCoef;

    const circleCenterBefore = localCircleCenterX - 0.2;
    const circleCenterAfter = localCircleCenterY + 0.1;

    const centerLineY = localCircleCenterY - r - i * gapWithStrokeWidth;
    const bottomLineX = localCircleCenterX + r + i * gapWithStrokeWidth;
    const topLineY1 = localCircleCenterY - rLastItem - charStrokeWidth;
    const strokeDasharray = `${(secondDash / 2) * 1.5},${secondDash}`;
    const bottomLineY1 = localCircleCenterY - r + charStrokeWidth;

    const topLineSize = topLineY1;
    const bottomLineSize = circleCenterAfter - (localCircleCenterY - r + charStrokeWidth);
    const circleSize = (2 * Math.PI * r) * (3 / 4);
    const centerLineSize = 100 - circleCenterBefore;
    const totalSize = topLineSize + bottomLineSize + circleSize + centerLineSize;

    const parts = divideNumber(item.progress, [
      calculateInterest(totalSize, topLineSize) * 100,
      calculateInterest(totalSize, bottomLineSize) * 100,
      calculateInterest(totalSize, circleSize) * 100,
      calculateInterest(totalSize, centerLineSize) * 100,
    ]);

    const fillCenterLineY = circleCenterBefore + ((circleCenterAfter) * parts[3]);
    const fillBottomLineX = bottomLineY1 + ((circleCenterAfter - bottomLineY1) * parts[1]);
    const fillTopLineY1 = topLineY1 * parts[0];

    const fillStrokeDasharray = `${(secondDash / 2) * (1.5 * parts[2])},${secondDash}`;

    return {
      newR,
      secondDash,
      centerLineY,
      bottomLineX,
      topLineY1,
      strokeDasharray,
      bottomLineY1,
      fillCenterLineY,
      fillBottomLineX,
      fillTopLineY1,
      fillStrokeDasharray,
      circleCenterBefore,
      circleCenterAfter,
      ...item,
    };
  });
}

const props = defineProps({
  data: {
    type: Array<IStroke>,
    required: true,
  },
  gap: {
    type: Number,
    default: 0.5,
    required: false
  },
  strokeWidth: {
    type: Number,
    required: false
  }, radius: {
    type: Number,
    required: false
  }, circleCenterX: {
    type: Number,
    required: false
  },
  circleCenterY: {
    type: Number,
    required: false
  },
});

const startValues: Record<number, {
  strokeWidth: number,
  r: number,
}> = {
  1: {
    strokeWidth: 4,
    r: 20,
  },
  2: {
    strokeWidth: 4,
    r: 20,
  },
  3: {
    strokeWidth: 4,
    r: 20,
  },
  4: {
    strokeWidth: 4,
    r: 20,
  },
  5: {
    strokeWidth: 4,
    r: 19,
  },
  6: {
    strokeWidth: 3,
    r: 19,
  },
  7: {
    strokeWidth: 3,
    r: 17,
  },
  8: {
    strokeWidth: 2.5,
    r: 17,
  },
  9: {
    strokeWidth: 2,
    r: 17,
  },
  10: {
    strokeWidth: 2,
    r: 16,
  },
};

const chartRef = ref();
const chartSize = ref(0);
const { strokes } = reactive<{
  strokes: IStrokeDetailed[]
}>({
  strokes: []
});

const localCircleCenterX = props.circleCenterX || 40;
const localCircleCenterY = props.circleCenterY || 60;
const charStrokeWidth = props.strokeWidth || startValues[props.data.length].strokeWidth;
const gapWithStrokeWidth = charStrokeWidth + props.gap;
const r = props.radius || startValues[props.data.length].r;
const circleCoef = 2 * Math.PI;
const rLastItem = r + ((props.data.length - 1) * gapWithStrokeWidth);

const processValues = props.data.reduce((acc, val) => {
  acc[val.id] = val.progress;
  return acc;
}, <Record<number, number>>{});

onMounted(() => {
  if (chartRef.value) {
    const sizeValue = Math.min(chartRef.value.clientWidth, chartRef.value.clientHeight);
    chartSize.value = sizeValue / 500;
  }
});

watch(() => props.data, (newVal: IStroke[]) => {
  animate({
    items: newVal
      .filter(e => processValues[e.id] !== e.progress)
      .map(e => ({ from: processValues[e.id], to: e.progress, id: e.id })),
    speed: 500
  });
}, { deep: true });

strokes.push(...updateStrokes(props.data));
</script>

<template>
  <div class="chart-wrapper">
    <svg ref="chartRef" class="chart" viewBox="0 0 100 100">
      <template v-for="stroke in strokes">
        <line :x1="stroke.bottomLineX" :x2="stroke.bottomLineX" :y1="stroke.topLineY1" y2="0"
          :stroke-width="charStrokeWidth" stroke="#cccccc" />
        <line :x1="stroke.bottomLineX" :x2="stroke.bottomLineX" :y1="stroke.circleCenterAfter"
          :y2="localCircleCenterY - r + charStrokeWidth" :stroke-width="charStrokeWidth" stroke="#cccccc" />
        <circle :r="stroke.newR" :cx="localCircleCenterX" :cy="localCircleCenterY" class="pie"
          :stroke-width="charStrokeWidth" stroke="#cccccc" :stroke-dasharray="stroke.strokeDasharray" fill="none" />
        <line :x1="stroke.circleCenterBefore" x2="100" :y1="stroke.centerLineY" :y2="stroke.centerLineY"
          :stroke-width="charStrokeWidth" stroke="#cccccc" />
        <line :x1="stroke.bottomLineX" :x2="stroke.bottomLineX" :y1="stroke.fillTopLineY1" y2="0"
          :stroke-width="charStrokeWidth" :stroke="stroke.color" />
        <line :x1="stroke.bottomLineX" :x2="stroke.bottomLineX" :y2="stroke.fillBottomLineX"
          :y1="localCircleCenterY - r + charStrokeWidth" :stroke-width="charStrokeWidth" :stroke="stroke.color" />
        <circle :r="stroke.newR" :cx="localCircleCenterX" :cy="localCircleCenterY" class="pie"
          :stroke-width="charStrokeWidth" :stroke="stroke.color" :stroke-dasharray="stroke.fillStrokeDasharray"
          fill="none" />
        <line :x1="stroke.circleCenterBefore" :x2="stroke.fillCenterLineY" :y1="stroke.centerLineY"
          :y2="stroke.centerLineY" :stroke-width="charStrokeWidth" :stroke="stroke.color" />
      </template>
    </svg>
    {{ props.circleCenterX }}
    <div class="chart-info" :style="{
      top: localCircleCenterY + '%',
      left: localCircleCenterX + '%',
      transform: `translate(-50%, -50%) scale(${1 * chartSize})`,
    }">
      <span class="main-text">
        9999
      </span>
      <span class="second-text">
        kgCO2e
      </span>
    </div>
  </div>
</template>

<style scoped>
.chart-wrapper {
  width: 500px;
  height: 500px;
  position: relative;

  .chart {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 100%;
    height: 100%;
  }

  .main-text {
    font-size: 32px;
  }

  .second-text {
    font-size: 16px;
    color: #b3b3b3;
  }

  .chart-info {
    position: absolute;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
  }
}
</style>
